/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.ManageAirlines;

import Business.Airline;
import Business.Airplane;
import Business.AirplaneFleet;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



public class CreateAirplane extends javax.swing.JPanel {

    /**
     * Creates new form CreateCarJPanel
     */

private TravelAgency airlineFleet ;
private JPanel userProcessContainer;
private String airlineName;
    private AirplaneFleet airplanefleet;
    public CreateAirplane(AirplaneFleet airplanefleet,JPanel userProcessContainer,String airlineName) {
        initComponents();
            this.airlineName = airlineName;
          this.userProcessContainer = userProcessContainer ;
          this.airlineFleet = airlineFleet ;
          this.airplanefleet = airplanefleet;
          //intitialTextField();
          clearFields();
        
    }
    
     
    private void clearFields()
        {
            airplaneIdTextField.setText("");
            modelNumberTextField.setText("");
            mfgYearTextField.setText("");
            manuCompanyTextField.setText("");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        airplaneNameTextField = new javax.swing.JTextField();
        modelNumberTextField = new javax.swing.JTextField();
        mfgYearTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        airplaneIdTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        manuCompanyTextField = new javax.swing.JTextField();
        backButtonViewAllPlanes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(925, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Airplane");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 760, -1));

        createButton.setBackground(new java.awt.Color(0, 0, 0));
        createButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 125, 47));
        add(airplaneNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 150, 30));
        add(modelNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 150, 30));
        add(mfgYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 150, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Airplane Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 117, 210, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Model Number:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 167, 210, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Manufacturing Year:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 217, 230, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("Airplane ID:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 267, 210, 30));
        add(airplaneIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 150, 30));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Manufacturing Company:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 317, 260, 30));
        add(manuCompanyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 150, 30));

        backButtonViewAllPlanes.setBackground(new java.awt.Color(0, 0, 0));
        backButtonViewAllPlanes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backButtonViewAllPlanes.setForeground(new java.awt.Color(255, 255, 255));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });
        add(backButtonViewAllPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 91, -1));
    }// </editor-fold>//GEN-END:initComponents
//    private void intitialTextField() {
//        modelNumberTextField.setText("");
//        mfgYearTextField.setText("");
//        airplaneNameTextField.setText("");
//        noOfSeatsTextField.setText("");
//       
//        comboUser.removeAllItems();
//        
//        for(Airline airline:airlineFleet.getAirlineFleet() ){
//            comboUser.addItem(airline.getNameOfAirline());
//        }
//        
//    }
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:     
        try {
            Integer.parseInt(mfgYearTextField.getText());
            Integer.parseInt(airplaneIdTextField.getText());
           
            
        }
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Manufacturing Year and Airplane ID should be numberic", "Error", 0);
        return;
        }
        
        
        if (airplaneNameTextField.getText().isEmpty() || modelNumberTextField.getText().isEmpty() ||
                manuCompanyTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All Fileds are mandatory. Please fill values in missing fields","Error",0);
        } else {
               
                Airplane airplane = airplanefleet.addAirplane();
                airplane.setAirplaneId(Integer.parseInt(airplaneIdTextField.getText()));
                airplane.setAirplaneName(airplaneNameTextField.getText());
                airplane.setAirline(airlineName);
                airplane.setManufacturingCompany(manuCompanyTextField.getText());
                  if(Integer.parseInt(mfgYearTextField.getText()) > 2020){
                      JOptionPane.showMessageDialog(null, "Give manufacturing year earlier than today","Error",0);
                      return;
                  }
                  else{                    
                airplane.setManufacturingYear(Integer.parseInt(mfgYearTextField.getText()));
                  }
                airplane.setModelNumber(modelNumberTextField.getText());

                JOptionPane.showMessageDialog(null, "Airplane Created Successfully");
                
                airplaneIdTextField.setText("");
                airplaneNameTextField.setText("");
                airplaneNameTextField.setText("");
                manuCompanyTextField.setText("");
                mfgYearTextField.setText("");
                modelNumberTextField.setText("");
                
             

            
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);         
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewAllPlanesPanel viewAllFlightsPanel  = (ViewAllPlanesPanel) component;
        viewAllFlightsPanel.populateAiplaneTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airplaneIdTextField;
    private javax.swing.JTextField airplaneNameTextField;
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField manuCompanyTextField;
    private javax.swing.JTextField mfgYearTextField;
    private javax.swing.JTextField modelNumberTextField;
    // End of variables declaration//GEN-END:variables
}
