/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirlines;

import Business.Airline;
import Business.AirplaneFleet;
import Business.FleetSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class CreateAirline extends javax.swing.JPanel {

    /**
     * Creates new form CreateCarJPanel
     */
    private Airline airline;
    private TravelAgency travelAgency;
    private JPanel userProcessContainer;

    public CreateAirline(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        this.airline = airline;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlineNameTextField = new javax.swing.JTextField();
        headQuartersTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createAirplaneButton = new javax.swing.JButton();
        backButtonViewAllPlanes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(airlineNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 132, -1));
        add(headQuartersTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 132, -1));
        add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 132, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Airline Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Headquarters:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Country:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, -1));

        createAirplaneButton.setBackground(new java.awt.Color(0, 0, 0));
        createAirplaneButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        createAirplaneButton.setForeground(new java.awt.Color(255, 255, 255));
        createAirplaneButton.setText("Create");
        createAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirplaneButtonActionPerformed(evt);
            }
        });
        add(createAirplaneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 160, 47));

        backButtonViewAllPlanes.setBackground(new java.awt.Color(0, 0, 0));
        backButtonViewAllPlanes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backButtonViewAllPlanes.setForeground(new java.awt.Color(255, 255, 255));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });
        add(backButtonViewAllPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 91, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Airline");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 813, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void intitialTextField() {
        headQuartersTextField.setText("");
        countryTextField.setText("");
        airlineNameTextField.setText("");

    }
    private void createAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirplaneButtonActionPerformed
      
        if(airlineNameTextField.getText().isEmpty() || headQuartersTextField.getText().isEmpty()||countryTextField.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "All values are mandatory", "Error", 0);
          return;
        }
        try {
            for (Map.Entry<String, Airline> it : travelAgency.getListOfAirline().entrySet()) {
                if (it.getKey().toString().equals(airlineNameTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "Exissting Airline", "Error", 0);
                    return;
                }
            }
            {                
                Airline airline = travelAgency.addAirline(airlineNameTextField.getText());
                airline.setNameOfAirline(airlineNameTextField.getText());
                airline.setMainHub(headQuartersTextField.getText());
                airline.setCountryOfOperation(countryTextField.getText());
                AirplaneFleet airplanefleet = new AirplaneFleet();
                airplanefleet.setAirline(airline);
                airline.setFleet(airplanefleet);
                FleetSchedule fleetSchedule = travelAgency.getSchedule().addFleetSchedule(airline);
                airline.setFleetschedule(fleetSchedule);
                fleetSchedule.setAirline(airline);
                JOptionPane.showMessageDialog(null, "Airline created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                airlineNameTextField.setText("");
                countryTextField.setText("");
                headQuartersTextField.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_createAirplaneButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineNameTextField;
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createAirplaneButton;
    private javax.swing.JTextField headQuartersTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
