/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.ManageAirlines;

import Business.Airline;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;




public class ManageAirline extends javax.swing.JPanel {

    /**
     * Creates new form CreateCarJPanel
     */

private TravelAgency travelAgency ;
private JPanel userProcessContainer;
    public ManageAirline(JPanel userProcessContainer ,TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.travelAgency = travelAgency ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAirlineButton = new javax.swing.JButton();
        listAllFlights = new javax.swing.JButton();
        listAirlinesButton = new javax.swing.JButton();
        backButtonViewAllPlanes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAirlineButton.setBackground(new java.awt.Color(0, 0, 0));
        createAirlineButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        createAirlineButton.setForeground(new java.awt.Color(255, 255, 255));
        createAirlineButton.setText("Create Airline");
        createAirlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlineButtonActionPerformed(evt);
            }
        });
        add(createAirlineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, 47));

        listAllFlights.setBackground(new java.awt.Color(0, 0, 0));
        listAllFlights.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        listAllFlights.setForeground(new java.awt.Color(255, 255, 255));
        listAllFlights.setText("List all Flights");
        listAllFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllFlightsActionPerformed(evt);
            }
        });
        add(listAllFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 190, 47));

        listAirlinesButton.setBackground(new java.awt.Color(0, 0, 0));
        listAirlinesButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        listAirlinesButton.setForeground(new java.awt.Color(255, 255, 255));
        listAirlinesButton.setText("List of Airlines");
        listAirlinesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAirlinesButtonActionPerformed(evt);
            }
        });
        add(listAirlinesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 190, 47));

        backButtonViewAllPlanes.setBackground(new java.awt.Color(0, 0, 0));
        backButtonViewAllPlanes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backButtonViewAllPlanes.setForeground(new java.awt.Color(255, 255, 255));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });
        add(backButtonViewAllPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 160, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Airlines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 9, 813, -1));
    }// </editor-fold>//GEN-END:initComponents
  /*  private void intitialTextField() {
        minSeatTextField.setText("");
        maxSeatTextField.setText("");
        mfgYrTextField.setText("");
        cityTextField.setText("");
        modelNoTextField.setText("");
        manufactureTextField.setText("");
        srnoTextField.setText("");
        ownerTextField.setText("");
        availableCheckBox.setSelected(false);
        certifiedCheckBox.setSelected(false);
    } */
    private void createAirlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlineButtonActionPerformed
        // TODO add your handling code here:
       CreateAirline   createAirlinePanel = new CreateAirline(userProcessContainer, travelAgency);
        userProcessContainer.add("ManageAirlineJPanel",createAirlinePanel);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer); 
        
        
    }//GEN-LAST:event_createAirlineButtonActionPerformed

    private void listAllFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllFlightsActionPerformed
        ViewAllFlightsPanel viewAllFlightsPanel = new ViewAllFlightsPanel(travelAgency,userProcessContainer);
        userProcessContainer.add("ListOfFlights",viewAllFlightsPanel);
        CardLayout cardLayout= (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_listAllFlightsActionPerformed

    private void listAirlinesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAirlinesButtonActionPerformed
        // TODO add your handling code here:
        ListAirlines listOfAirlinesPanel = new ListAirlines(travelAgency,userProcessContainer);
        userProcessContainer.add("ListOfAirline",listOfAirlinesPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_listAirlinesButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JButton createAirlineButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listAirlinesButton;
    private javax.swing.JButton listAllFlights;
    // End of variables declaration//GEN-END:variables
}
