/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirlines;

import Business.Airline;
import Business.AirplaneFleet;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class UpdateAirlines extends javax.swing.JPanel {

    /**
     * Creates new form UpdateAirlines
     */
    private Airline airline;
    private JPanel userProcessContainer;
    public UpdateAirlines(JPanel userProcessContainer ,Airline airline) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.airline = airline ;
        airlineNameTextField.setText(airline.getNameOfAirline());
        hubTextField.setText(airline.getMainHub());
        countryTextField.setText(airline.getCountryOfOperation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlineNameTextField = new javax.swing.JTextField();
        hubTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveAirlineButton = new javax.swing.JButton();
        updateAirlineButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButtonViewAllPlanes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        airlineNameTextField.setEnabled(false);
        add(airlineNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 132, -1));

        hubTextField.setEnabled(false);
        add(hubTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 132, -1));

        countryTextField.setEnabled(false);
        add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 132, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Airline Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hub:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Country:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, -1));

        saveAirlineButton.setBackground(new java.awt.Color(0, 0, 0));
        saveAirlineButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        saveAirlineButton.setForeground(new java.awt.Color(255, 255, 255));
        saveAirlineButton.setText("Save");
        saveAirlineButton.setEnabled(false);
        saveAirlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAirlineButtonActionPerformed(evt);
            }
        });
        add(saveAirlineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 125, 47));

        updateAirlineButton.setBackground(new java.awt.Color(0, 0, 0));
        updateAirlineButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        updateAirlineButton.setForeground(new java.awt.Color(255, 255, 255));
        updateAirlineButton.setText("Update");
        updateAirlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirlineButtonActionPerformed(evt);
            }
        });
        add(updateAirlineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 125, 47));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of Airlines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 813, -1));

        backButtonViewAllPlanes.setBackground(new java.awt.Color(0, 0, 0));
        backButtonViewAllPlanes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backButtonViewAllPlanes.setForeground(new java.awt.Color(255, 255, 255));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });
        add(backButtonViewAllPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 91, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveAirlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAirlineButtonActionPerformed
        // TODO add your handling code here:
        //CreateAirplaneJPanel   createAirplanePanel = new CreateAirplaneJPanel(userProcessContainer, airlineFleet);
        // userProcessContainer.add("CreateAirplaneJPanel",createAirplanePanel);
        // CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        // cardlayout.next(userProcessContainer);
        try
        {
            airline.setNameOfAirline(airlineNameTextField.getText());
            airline.setMainHub(hubTextField.getText());
            airline.setCountryOfOperation(countryTextField.getText());
            JOptionPane.showMessageDialog(null, "Airline updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            saveAirlineButton.setEnabled(false);
            updateAirlineButton.setEnabled(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Existing Airline", "Error", 0);
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveAirlineButtonActionPerformed

    private void updateAirlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirlineButtonActionPerformed
        // TODO add your handling code here:
        updateAirlineButton.setEnabled(false);
        airlineNameTextField.setEnabled(true);
        hubTextField.setEnabled(true);
        countryTextField.setEnabled(true);
        saveAirlineButton.setEnabled(true);
    }//GEN-LAST:event_updateAirlineButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);         
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ListAirlines listAirlines  = (ListAirlines) component;
        listAirlines.populateComboBox();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineNameTextField;
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField hubTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton saveAirlineButton;
    private javax.swing.JButton updateAirlineButton;
    // End of variables declaration//GEN-END:variables
}
