/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.BookFlight;

import Business.Airline;
import Business.AirplaneFleet;
import Business.FleetSchedule;
import Business.Person;
import Business.TravelAgency;
import Interface.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;




public class Customer extends javax.swing.JPanel {
    
    private TravelAgency travelAgency ;
    private JPanel userProcessContainer;
    Person person ;
    
    public void CreatePersonObject(){
          Person person= travelAgency.getPersonDirectory().addPerson();
          this.person = person;
          customerIDTextField.setText(person.getPersonIdIncremental() + "" );
    }
    public Customer(JPanel userProcessContainer ,TravelAgency travelAgency) {
        initComponents();
          this.userProcessContainer = userProcessContainer ;
          this.travelAgency = travelAgency ; 
          CreatePersonObject();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerIDTextField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        customerEmailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createCustomerButton = new javax.swing.JButton();
        addMoreCustButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButtonViewAllPlanes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(925, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerIDTextField.setEnabled(false);
        add(customerIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 132, -1));
        add(customerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 132, -1));
        add(customerEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 132, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 119, 150, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 170, 170, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Country Email ID:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 219, 180, -1));

        createCustomerButton.setBackground(new java.awt.Color(51, 51, 51));
        createCustomerButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        createCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        createCustomerButton.setText("Create Customer");
        createCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerButtonActionPerformed(evt);
            }
        });
        add(createCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 280, 47));

        addMoreCustButton.setBackground(new java.awt.Color(51, 51, 51));
        addMoreCustButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        addMoreCustButton.setForeground(new java.awt.Color(255, 255, 255));
        addMoreCustButton.setText("Add Another Customer");
        addMoreCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreCustButtonActionPerformed(evt);
            }
        });
        add(addMoreCustButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, 47));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 813, -1));

        backButtonViewAllPlanes.setBackground(new java.awt.Color(255, 51, 102));
        backButtonViewAllPlanes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backButtonViewAllPlanes.setForeground(new java.awt.Color(255, 255, 255));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });
        add(backButtonViewAllPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 91, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void intitialTextField() {
        customerNameField.setText("");
        customerEmailField.setText("");
        customerIDTextField.setText("");
        
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout =  (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed
    boolean emailIdPatternCorrect(){
        Pattern p = Pattern.compile(".+@[a-zA-Z0-9]+\\.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(customerEmailField.getText());
        return m.matches();
    }
    private void createCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerButtonActionPerformed
        // TODO add your handling code here:
    
            try
            {            
                person.setName(customerNameField.getText());
                person.setPersonId(Integer.parseInt(customerIDTextField.getText())); 
                
                if (!emailIdPatternCorrect()) {

                    customerEmailField.setBorder(BorderFactory.createLineBorder(Color.RED));
                    JOptionPane.showMessageDialog(null, "Email id not correct");
                    return;
                
                }
                person.setEmailId(customerEmailField.getText());
                customerEmailField.setEnabled(false);
                customerNameField.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Customer Created Successfully.");
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Incorrect Person ID", "Error", 0);
                e.printStackTrace();
            }
    }//GEN-LAST:event_createCustomerButtonActionPerformed

    private void addMoreCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoreCustButtonActionPerformed
        // TODO add your handling code here:
         customerEmailField.setText("");
         customerNameField.setText("");
        customerEmailField.setEnabled(true);
        customerNameField.setEnabled(true);
        CreatePersonObject();
    }//GEN-LAST:event_addMoreCustButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoreCustButton;
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JTextField customerEmailField;
    private javax.swing.JTextField customerIDTextField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
