/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.BookFlight;

import Business.Airline;
import Business.AirplaneFleet;
import Business.FleetSchedule;
import Business.Person;
import Business.TravelAgency;
import Interface.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;




public class ManageBooking extends javax.swing.JPanel {
    
    private TravelAgency travelAgency ;
    private JPanel userProcessContainer;
    public ManageBooking(JPanel userProcessContainer ,TravelAgency travelAgency) {
        initComponents();
          this.userProcessContainer = userProcessContainer ;
          this.travelAgency = travelAgency ;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCustomerButton = new javax.swing.JButton();
        bookFlightButton = new javax.swing.JButton();
        backButtonViewAllPlanes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(925, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createCustomerButton.setBackground(new java.awt.Color(0, 0, 0));
        createCustomerButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        createCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        createCustomerButton.setText("Create Customer");
        createCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerButtonActionPerformed(evt);
            }
        });
        add(createCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 240, 47));

        bookFlightButton.setBackground(new java.awt.Color(0, 0, 0));
        bookFlightButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bookFlightButton.setForeground(new java.awt.Color(255, 255, 255));
        bookFlightButton.setText("Book Flight");
        bookFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightButtonActionPerformed(evt);
            }
        });
        add(bookFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 240, 47));

        backButtonViewAllPlanes.setBackground(new java.awt.Color(51, 51, 51));
        backButtonViewAllPlanes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backButtonViewAllPlanes.setForeground(new java.awt.Color(255, 255, 255));
        backButtonViewAllPlanes.setText("Back");
        backButtonViewAllPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewAllPlanesActionPerformed(evt);
            }
        });
        add(backButtonViewAllPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 91, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Bookings");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 9, 690, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void intitialTextField() {
        
        
    }
    private void createCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerButtonActionPerformed
        // TODO add your handling code here:
    
        Customer   customer = new Customer(userProcessContainer, travelAgency);
        userProcessContainer.add("ManageAirlineJPanel",customer);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
    }//GEN-LAST:event_createCustomerButtonActionPerformed

    private void bookFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightButtonActionPerformed
        // TODO add your handling code here:
        SearchAndBook  searchAndBook = new SearchAndBook(userProcessContainer, travelAgency);
        userProcessContainer.add("ManageAirlineJPanel",searchAndBook);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
    }//GEN-LAST:event_bookFlightButtonActionPerformed

    private void backButtonViewAllPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewAllPlanesActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonViewAllPlanesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonViewAllPlanes;
    private javax.swing.JButton bookFlightButton;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
